server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dorun-dorun

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/dorundorun?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf8mb4&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username:
    password:

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      database: dorundorun
