spring:
  application:
    name: dorun-dorun

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/dorundorun?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username:
    password:

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      username: qweqwe
      password: 123
      database: qwerqwer

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000  # 1 hour in milliseconds
